# .streamlit/secrets.toml (Este archivo SÓLO para desarrollo local)

# Conexión LOCAL (para cuando ejecutas Streamlit en tu máquina)
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "entelrm"

# Opcional: También puedes definir la cadena completa aquí si prefieres
# DB_CONNECTION_STRING_LOCAL = "postgresql+psycopg2://postgres:postgres@localhost:5432/entelrm"